<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>KUKULCAN.SharedKernel.Auth.PostgreSQL.Integration</RootNamespace>
    <AssemblyName>KUKULCAN.SharedKernel.Auth.PostgreSQL.Integration</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../KUKULCAN.SharedKernel/Source/KUKULCAN.SharedKernel/KUKULCAN.SharedKernel.csproj" />
    <ProjectReference Include="../../../../KUKULCAN.SharedKernel.Database/Source/KUKULCAN.SharedKernel.Database/KUKULCAN.SharedKernel.Database.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.*" />
    <PackageReference Include="NUnit.Analyzers" Version="4.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="coverlet.collector" Version="6.*" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="TestResults\" />
  </ItemGroup>

</Project>
