// <auto-generated />
using System;
using KUKULCAN.SharedKernel.Auth.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KUKULCAN.SharedKernel.Auth.Migrations.MySQL.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20261002124109_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthFederatedIdentityEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subject")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("FederatedIdentities");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthTenantMembershipEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "TenantId");

                    b.ToTable("TenantMemberships");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthUserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthFederatedIdentityEntity", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.Auth.Entities.AuthUserEntity", "User")
                        .WithMany("FederatedIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthTenantMembershipEntity", b =>
                {
                    b.HasOne("KUKULCAN.SharedKernel.Auth.Entities.AuthUserEntity", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KUKULCAN.SharedKernel.Auth.Entities.AuthUserEntity", b =>
                {
                    b.Navigation("FederatedIdentities");

                    b.Navigation("TenantMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
