<Project>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
        <SolutionDir>$(MSBuildThisFileDirectory)..\..\</SolutionDir>
        <PackageId>$(AssemblyName)</PackageId>
        <Version>$(VersionPrefix)</Version>
        <Authors>Kukulcán Software Designer</Authors>
        <Company>Kukulcán Software Designer</Company>
        <Copyright>GPL 2026 Kukulcán Software Designer</Copyright>
        <PackageProjectUrl>https://www.kukulcan.org.mx/Software/SharedKernel/Autentication</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageOutputPath>$(SolutionDir)NuGet\</PackageOutputPath>
        <PackageTags>kukulcan;sharedkernel;autentication</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>
            Compared with version 1.1.3, this release updates the KUKULCAN.SharedKernel.Database dependency from 1.0.4 to 1.1.0, bringing the latest shared database infrastructure and configuration improvements into the authentication package. The Auth package version is also advanced to 1.1.4 to reflect this dependency update. No other authentication API or behavioral changes are introduced by this revision.
        </PackageReleaseNotes>
        <RepositoryUrl>https://github.com/Kukulcan-Software-Designer/KUKULCAN.SharedKernel.Auth</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>
            Provides authentication and authorization components for the KUKULCAN architecture, including local authentication, federated credential validation, multi-tenant identity management, user and tenant membership handling, and authentication infrastructure.
            Designed to provide consistent, reusable, and secure authentication capabilities across KUKULCAN applications and services.
        </Description>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="$(MSBuildThisFileDirectory)..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>