<Project>
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <GeneratePackageOnBuild Condition="'$(Configuration)'=='Release'">true</GeneratePackageOnBuild>
        <SolutionDir>$(MSBuildThisFileDirectory)..\..\</SolutionDir>
        <PackageId>$(AssemblyName)</PackageId>
        <Version>$(VersionPrefix)</Version>
        <Authors>Kukulcán Software Designer</Authors>
        <Company>Kukulcán Software Designer</Company>
        <Copyright>GPL 2026 Kukulcán Software Designer</Copyright>
        <PackageProjectUrl>https://www.kukulcan.org.mx/Software/SharedKernel/Autentication</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageOutputPath>$(SolutionDir)NuGet\</PackageOutputPath>
        <PackageTags>kukulcan;sharedkernel;autentication</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageReleaseNotes>
            Initial release of KUKULCAN.SharedKernel.Auth. Provides local and federated authentication, authorization, multi-tenant identity management, credential validation, user and tenant membership handling, and authentication-related infrastructure for KUKULCAN applications and services.
        </PackageReleaseNotes>
        <RepositoryUrl>https://github.com/Kukulcan-Software-Designer/KUKULCAN.SharedKernel.Auth</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Description>
            Provides authentication and authorization components for the KUKULCAN architecture, including local authentication, federated credential validation, multi-tenant identity management, user and tenant membership handling, and authentication infrastructure.
            Designed to provide consistent, reusable, and secure authentication capabilities across KUKULCAN applications and services.
        </Description>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Include="$(MSBuildThisFileDirectory)..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>
