<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>KUKULCAN.SharedKernel.Auth</RootNamespace>
    <AssemblyName>KUKULCAN.SharedKernel.Auth</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KUKULCAN.SharedKernel" Version="1.0.0" />
    <PackageReference Include="KUKULCAN.SharedKernel.Database" Version="1.0.2" />
  </ItemGroup>

</Project>
