<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>KUKULCAN.SharedKernel.Auth</RootNamespace>
    <AssemblyName>KUKULCAN.SharedKernel.Auth</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../KUKULCAN.SharedKernel/Source/KUKULCAN.SharedKernel/KUKULCAN.SharedKernel.csproj" />
    <ProjectReference Include="../../../../KUKULCAN.SharedKernel.Database/Source/KUKULCAN.SharedKernel.Database/KUKULCAN.SharedKernel.Database.csproj" />
  </ItemGroup>

</Project>
