<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <LangVersion>latestmajor</LangVersion>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
      <IsPackable>false</IsPackable>
      <IsTestProject>true</IsTestProject>
      <RootNamespace>KUKULCAN.SharedKernel.Auth.UnitTests</RootNamespace>
      <AssemblyName>KUKULCAN.SharedKernel.Auth.UnitTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Source/KUKULCAN.SharedKernel.Auth/KUKULCAN.SharedKernel.Auth.csproj" />
    <Using Include="KUKULCAN.SharedKernel.Auth.Authentication.Federated" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Api/AuthenticationApiTests.cs" />
    <Compile Remove="FederatedAuthenticationServiceTests.cs" />
    <Compile Remove="FederatedAuthenticationProvidersTests.cs" />
    <Compile Remove="ValidatorTests/AppleCredentialValidatorTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.*" />
    <PackageReference Include="NUnit.Analyzers" Version="4.*" />
    <PackageReference Include="KUKULCAN.SharedKernel" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.*" />
    <PackageReference Include="Moq" Version="4.*" />
    <PackageReference Include="FluentAssertions" Version="8.*" />
    <PackageReference Include="AutoFixture" Version="4.*" />
    <PackageReference Include="AutoFixture.AutoMoq" Version="4.*" />
    <PackageReference Include="coverlet.collector" Version="6.*" />
  </ItemGroup>

</Project>