<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>KUKULCAN.SharedKernel.Auth.Client.UnitTests</RootNamespace>
    <AssemblyName>KUKULCAN.SharedKernel.Auth.Client.UnitTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../SourceClient/KUKULCAN.SharedKernel.Auth.Client/KUKULCAN.SharedKernel.Auth.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.*" />
    <PackageReference Include="NUnit" Version="4.*" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.*" />
    <PackageReference Include="NUnit.Analyzers" Version="4.*" />
  </ItemGroup>
</Project>
